# -Dspring.profiles.active=server1
server:
  port: 7901

eureka:
  instance:
    hostname: eureka-7901
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/,http://eureka-7903:7903/eureka/

spring:
  application:
    name: Eureka