spring:
  application:
    name: provider
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
  instance:
    metadata-map:
      dalao: lisz-hahaha
